/**
 * GENERATED FILE — do not edit by hand.
 * Source: Sanity Content Lake (project 0uqx6fxe, dataset production, published perspective)
 * Regenerated by scripts/generate-articles.mjs on every build.
 * When empty, src/data/articles.ts falls back to the legacy TypeScript articles.
 */
import type {Article} from './articles';

export const generatedSource: 'sanity' | 'none' = "sanity";

export const generatedArticles: Article[] = [];
